FROM cm2network/steamcmd:root

LABEL maintainer="Lennard Indlekofer <info@lennard0711.eu>"

ENV STEAM_HOME_DIR=/home/steam \
    STEAM_APP_DIR=/home/steam/gm \
    STEAM_CMD_DIR=/home/steam/steamcmd \
    STEAM_API_KEY=false \
    STEAM_COLLECTION=1297312862 \
    GMOD_GAMEMODE=terrortown \
    GMOD_CSS=false \
    GMOD_TF2=false \
    GMOD_DEFAULT_MAP=ttt_minecraft_b5 \
    GMOD_PLAYERS=16 \
    GMOD_NO_CONF=false \
    HOSTNAME="lennard0711 dockerized GMod Server" \
    RCON_PASSWORD=changeme \
    SV_LOGBANS=1 \
    SV_LOGECHO=1 \
    SV_LOGFILE=1 \
    SV_LOG_ONEFILE=0 \
    SV_MINRATE=3500 \
    SV_MAXRATE=0 \
    SV_MAXUPDATERATE=33 \
    SV_MINUPDATERATE=10 \
    NET_MAXFILESIZE=60 \
    DECALFREQUENCY=10 \
    TTT_PREPTIME_SECONDS=25 \
    TTT_FIRSTPREPTIME=30 \
    TTT_POSTTIME_SECONDS=20 \
    TTT_HASTE=1 \
    TTT_HASTE_STARTING_MINUTES=5 \
    TTT_HASTE_MINUTES_PER_DEATH=0.5 \
    TTT_ROUNDTIME_MINUTES=5 \
    TTT_ROUND_LIMIT=6 \
    TTT_TIME_LIMIT_MINUTES=90 \
    TTT_ALWAYS_USE_MAPCYCLE=0 \
    TTT_TRAITOR_PCT=0.34 \
    TTT_TRAITOR_MAX=6 \
    TTT_DETECTIVE_PCT=0.15 \
    TTT_DETECTIVE_MAX=2 \
    TTT_DETECTIVE_MIN_PLAYERS=7 \
    TTT_MINIMUM_PLAYERS=2 \
    TTT_POSTROUND_DM=1 \
    TTT_NO_NADE_THROW_DURING_PREP=0 \
    TTT_RAGDOLL_PINNING=1 \
    TTT_RAGDOLL_PINNING_INNOCENTS=1 \
    TTT_KARMA=1 \
    TTT_KARMA_STRICT=1 \
    TTT_KARMA_STARTING=1000 \
    TTT_KARMA_MAX=1000\
    TTT_KARMA_RATIO=0.001 \
    TTT_KARMA_KILL_PENALTY=15 \
    TTT_KARMA_ROUND_INCREMENT=5 \
    TTT_KARMA_CLEAN_BONUS=100 \
    TTT_KARMA_TRAITORDMG_RATIO=0.0003 \
    TTT_KARMA_TRAITORKILL_BONUS=150 \
    TTT_KARMA_LOW_AUTOKICK=1 \
    TTT_KARMA_LOW_AMOUNT=400 \
    TTT_KARMA_LOW_BAN=1 \
    TTT_KARMA_LOW_BAN_MINUTES=300 \
    TTT_KARMA_PERSIST=1 \
    TTT_KARMA_DEBUGSPAM=0 \
    TTT_KARMA_CLEAN_HALF=0.25 \
    TTT_USE_WEAPON_SPAWN_SCRIPTS=1 \
    TTT_CREDITS_STARTING=2 \
    TTT_CREDITS_AWARD_PCT=0.4 \
    TTT_CREDITS_AWARD_SIZE=1 \
    TTT_CREDITS_AWARD_REPEAT=1 \
    TTT_CREDITS_DETECTIVEKILL=1 \
    TTT_DET_CREDITS_STARTING=1 \
    TTT_DET_CREDITS_TRAITORKILL=0 \
    TTT_DET_CREDITS_TRAITORDEAD=1 \
    TTT_SPEC_PROP_CONTROL=1 \
    TTT_SPEC_PROP_BASE=10 \
    TTT_SPEC_PROP_MAXPENALTY=-6 \
    TTT_SPEC_PROP_MAXBONUS=16 \
    TTT_SPEC_PROP_FORCE=100 \
    TTT_SPEC_PROP_RECHARGETIME=0.75 \
    TTT_IDLE_LIMIT=120 \
    TTT_NAMECHANGE_KICK=0 \
    TTT_NAMECHANGE_BANTIME=0 \
    TTT_DETECTIVE_HATS=1 \
    TTT_PLAYERCOLOR_MODE=1 \
    TTT_RAGDOLL_COLLIDE=1 \
    TTT_BOTS_ARE_SPECTATORS=0 \
    TTT_DEBUG_PREVENTWIN=0 \
    TTT_LOCATIONAL_VOICE=0 \
    TTT_ALLOW_DISCOMB_JUMP=1 \
    TTT_SPAWN_WAVE_INTERVAL=3 

ADD entrypoint.sh ${STEAM_HOME_DIR}/entrypoint.sh

RUN set -x \
    && chmod 755 ${STEAM_HOME_DIR}/entrypoint.sh \
    && chown -R steam:steam ${STEAM_HOME_DIR}

USER steam
RUN set -x \
    && ${STEAM_CMD_DIR}/steamcmd.sh +login anonymous +force_install_dir ${STEAM_APP_DIR} +app_update 4020 +quit \
    && echo "gamemode ${GMOD_GAMEMODE}" > ${STEAM_APP_DIR}/garrysmod/cfg/autoexec.cfg

EXPOSE 27015/tcp 27015/udp
WORKDIR ${STEAM_HOME_DIR}
ENTRYPOINT ["./entrypoint.sh"]
