FROM cm2network/steamcmd:root

LABEL maintainer="Lennard Indlekofer <info@lennard0711.eu>"

ENV STEAM_HOME_DIR /home/steam
ENV STEAM_APP_DIR /home/steam/gm
ENV STEAM_CMD_DIR /home/steam/steamcmd
ENV STEAM_API_KEY false
ENV STEAM_COLLECTION 1297312862

ENV GMOD_GAMEMODE terrortown
ENV GMOD_CSS false
ENV GMOD_TF2 false
ENV GMOD_DEFAULT_MAP gm_construct
ENV GMOD_PLAYERS 16

ADD entrypoint.sh ${STEAM_HOME_DIR}/entrypoint.sh

RUN set -x \
    && chmod 755 ${STEAM_HOME_DIR}/entrypoint.sh \
    && chown -R steam:steam ${STEAM_HOME_DIR}

USER steam
RUN set -x \
    && ${STEAM_CMD_DIR}/steamcmd.sh +login anonymous +force_install_dir ${STEAM_APP_DIR} +app_update 4020 +quit \
    && echo "gamemode ${GMOD_GAMEMODE}" > ${STEAM_APP_DIR}/garrysmod/cfg/autoexec.cfg

EXPOSE 27015/tcp 27015/udp

ENV HOSTNAME "lennard0711 dockerized GMod Server"
ENV RCON_PASSWORD changeme
ENV SV_LOGBANS 1
ENV SV_LOGECHO 1
ENV SV_LOGFILE 1
ENV SV_LOG_ONEFILE 0
ENV SV_MINRATE 3500
ENV SV_MAXRATE 0
ENV SV_MAXUPDATERATE 33
ENV SV_MINUPDATERATE 10
ENV NET_MAXFILESIZE 60
ENV DECALFREQUENCY 10

ENV TTT_PREPTIME_SECONDS 25
ENV TTT_FIRSTPREPTIME 30
ENV TTT_POSTTIME_SECONDS 20
ENV TTT_HASTE 1
ENV TTT_HASTE_STARTING_MINUTES 5
ENV TTT_HASTE_MINUTES_PER_DEATH 0.5
ENV TTT_ROUNDTIME_MINUTES 5
ENV TTT_ROUND_LIMIT 6
ENV TTT_TIME_LIMIT_MINUTES 90
ENV TTT_ALWAYS_USE_MAPCYCLE 0
ENV TTT_TRAITOR_PCT 0.34
ENV TTT_TRAITOR_MAX 6
ENV TTT_DETECTIVE_PCT 0.15
ENV TTT_DETECTIVE_MAX 2
ENV TTT_DETECTIVE_MIN_PLAYERS 7
ENV TTT_MINIMUM_PLAYERS 2
ENV TTT_POSTROUND_DM 1
ENV TTT_NO_NADE_THROW_DURING_PREP 0
ENV TTT_RAGDOLL_PINNING 1
ENV TTT_RAGDOLL_PINNING_INNOCENTS 1
ENV TTT_KARMA 1
ENV TTT_KARMA_STRICT 1
ENV TTT_KARMA_STARTING 1000
ENV TTT_KARMA_MAX 1000
ENV TTT_KARMA_RATIO 0.001
ENV TTT_KARMA_KILL_PENALTY 15
ENV TTT_KARMA_ROUND_INCREMENT 5
ENV TTT_KARMA_CLEAN_BONUS 100
ENV TTT_KARMA_TRAITORDMG_RATIO 0.0003
ENV TTT_KARMA_TRAITORKILL_BONUS 150
ENV TTT_KARMA_LOW_AUTOKICK 1
ENV TTT_KARMA_LOW_AMOUNT 400
ENV TTT_KARMA_LOW_BAN 1
ENV TTT_KARMA_LOW_BAN_MINUTES 300
ENV TTT_KARMA_PERSIST 1
ENV TTT_KARMA_DEBUGSPAM 0
ENV TTT_KARMA_CLEAN_HALF 0.25
ENV TTT_USE_WEAPON_SPAWN_SCRIPTS 1
ENV TTT_CREDITS_STARTING 2
ENV TTT_CREDITS_AWARD_PCT 0.4
ENV TTT_CREDITS_AWARD_SIZE 1
ENV TTT_CREDITS_AWARD_REPEAT 1
ENV TTT_CREDITS_DETECTIVEKILL 1
ENV TTT_DET_CREDITS_STARTING 1
ENV TTT_DET_CREDITS_TRAITORKILL 0
ENV TTT_DET_CREDITS_TRAITORDEAD 1
ENV TTT_SPEC_PROP_CONTROL 1
ENV TTT_SPEC_PROP_BASE 10
ENV TTT_SPEC_PROP_MAXPENALTY -6
ENV TTT_SPEC_PROP_MAXBONUS 16
ENV TTT_SPEC_PROP_FORCE 100
ENV TTT_SPEC_PROP_RECHARGETIME 0.75
ENV TTT_IDLE_LIMIT 120
ENV TTT_NAMECHANGE_KICK 0
ENV TTT_NAMECHANGE_BANTIME 0
ENV TTT_DETECTIVE_HATS 1
ENV TTT_PLAYERCOLOR_MODE 1
ENV TTT_RAGDOLL_COLLIDE 1
ENV TTT_BOTS_ARE_SPECTATORS 0
ENV TTT_DEBUG_PREVENTWIN 0
ENV TTT_LOCATIONAL_VOICE 0
ENV TTT_ALLOW_DISCOMB_JUMP 1
ENV TTT_SPAWN_WAVE_INTERVAL 3

WORKDIR ${STEAM_HOME_DIR}
ENTRYPOINT ["./entrypoint.sh"]