#!/bin/bash

echo 'hostname "Oktopoden in Verräter Stadt"
rcon_password    	"geheimesPasswort"
sv_password "analsex123"
sv_logbans       	1
sv_logecho       	1
sv_logfile       	1
sv_log_onefile   	0

ttt_preptime_seconds 25
ttt_firstpreptime 30
ttt_posttime_seconds 20
ttt_haste 1
ttt_haste_starting_minutes 5
ttt_haste_minutes_per_death 0.5
ttt_roundtime_minutes 5
ttt_round_limit 6
ttt_time_limit_minutes 90
ttt_always_use_mapcycle 0
ttt_traitor_pct 0.34
ttt_traitor_max 6
ttt_detective_pct 0.15
ttt_detective_max 2
ttt_detective_min_players 7
ttt_minimum_players 2
ttt_postround_dm 1
ttt_no_nade_throw_during_prep 0
ttt_ragdoll_pinning 1
ttt_ragdoll_pinning_innocents 1
ttt_karma 1
ttt_karma_strict 1
ttt_karma_starting 1000
ttt_karma_max 1000
ttt_karma_ratio 0.001
ttt_karma_kill_penalty 15
ttt_karma_round_increment 5
ttt_karma_clean_bonus 100
ttt_karma_traitordmg_ratio 0.0003
ttt_karma_traitorkill_bonus 150
ttt_karma_low_autokick 1
ttt_karma_low_amount 400
ttt_karma_low_ban 1
ttt_karma_low_ban_minutes 300
ttt_karma_persist 1
ttt_karma_debugspam 0
ttt_karma_clean_half 0.25
ttt_use_weapon_spawn_scripts 1
ttt_credits_starting 2
ttt_credits_award_pct 0.4
ttt_credits_award_size 1
ttt_credits_award_repeat 1
ttt_credits_detectivekill 1
ttt_det_credits_starting 1
ttt_det_credits_traitorkill 0
ttt_det_credits_traitordead 1
ttt_spec_prop_control 1
ttt_spec_prop_base 10
ttt_spec_prop_maxpenalty -6
ttt_spec_prop_maxbonus 16
ttt_spec_prop_force 100
ttt_spec_prop_rechargetime 0.75
ttt_idle_limit 120
ttt_namechange_kick 0
ttt_namechange_bantime 0
ttt_detective_hats 1
ttt_playercolor_mode 1
ttt_ragdoll_collide 1
ttt_bots_are_spectators 0
ttt_debug_preventwin 0
ttt_locational_voice 0
ttt_allow_discomb_jump 1
ttt_spawn_wave_interval 3
net_maxfilesize  	60
sv_minrate       	3500
sv_maxrate       	0
decalfrequency   	10
sv_maxupdaterate 	33
// Minimale Tickrate der Physic
sv_minupdaterate 	10' > ${STEAM_APP_DIR}/garrysmod/cfg/server.cfg